#!/usr/bin/env python3
"""generate-mark.py — build the SARC four-row mark SVG partial from the font.

Extracts the lowercase glyph outlines for "s a r c" from Nasalization and lays
them out as the four-row landing mark described in CLAUDE.md:

  Row 1  stable, readable          (never transforms)
  Row 2  active transform layer    (JS mutates individual letters)
  Row 3  vertical reflection of Row 2   — SVG <use> + matrix, no own state
  Row 4  vertical reflection of Row 1   — SVG <use> + matrix, no own state

Adjacent rows overlap by exactly one horizontal-bar height, so their horizontal
strokes coincide and fuse — the woven, coupled look of the original mark. The
figure is symmetric about its vertical centre (the reflection axis).

The glyph paths are baked into the committed partial, so the site ships no font
and needs no font CDN. Re-run with `make mark` only when the letterforms change.

Requires: fonttools + Pillow (pip install fonttools Pillow).
Font: design/fonts/Nasalization-Rg.otf
"""

import os
from fontTools.ttLib import TTFont
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.boundsPen import BoundsPen
from PIL import Image, ImageFont, ImageDraw

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FONT_PATH = os.path.join(ROOT, "design/fonts/Nasalization-Rg.otf")
OUT = os.path.join(ROOT, "layouts/partials/mark.html")
WORD_OUT = os.path.join(ROOT, "layouts/partials/wordmark.html")

TRACK = 40          # letter tracking (font units)
PADX = 90           # horizontal padding (font units)
WTRACK = 55         # wordmark tracking (font units) — the header/footer logotype

font = TTFont(FONT_PATH)
cmap = font.getBestCmap()
gs = font.getGlyphSet()
UPM = font["head"].unitsPerEm


def glyph(ch):
    g = gs[cmap[ord(ch)]]
    sp = SVGPathPen(gs); g.draw(sp)
    bp = BoundsPen(gs); g.draw(bp)
    return {"char": ch, "adv": g.width, "path": sp.getCommands(), "bounds": bp.bounds}


def bar_thickness():
    """Horizontal stroke height, in font units. Render each letter at em=UPM
    (so pixels == font units) and measure the solid run down from the top of a
    top-bar column; take the value the letters agree on."""
    pil = ImageFont.truetype(FONT_PATH, UPM)
    vals = []
    for ch in "sac":  # letters with a flat top bar
        img = Image.new("L", (UPM * 2, UPM * 2), 0)
        ImageDraw.Draw(img).text((UPM // 2, UPM // 2), ch, fill=255, font=pil)
        px = img.load(); W, H = img.size
        cols = [x for x in range(W) if any(px[x, y] > 128 for y in range(0, H, 2))]
        rows = [y for y in range(H) if any(px[x, y] > 128 for x in range(0, W, 2))]
        x0, x1, y0 = min(cols), max(cols), min(rows)
        top = [x for x in range(x0, x1 + 1) if px[x, y0 + 2] > 128]
        tx = top[len(top) // 2]
        t = 0
        for y in range(y0, H):
            if px[tx, y] > 128:
                t += 1
            else:
                break
        vals.append(t)
    return max(set(vals), key=vals.count)  # modal thickness


L = [glyph(c) for c in "sarc"]
C = max(g["bounds"][3] for g in L)      # body height (top of the letters)
BAR = bar_thickness()                    # horizontal bar height (overlap amount)

xs, x = [], PADX
for g in L:
    xs.append(x)
    x += g["adv"] + TRACK
W = x - TRACK + PADX

H = 4 * C - 3 * BAR                      # four rows, three one-bar overlaps

# Each row is upright or vertically flipped so adjacent rows meet as true mirrors
# sharing one horizontal bar. Rows are reflected across the figure's centre in
# pairs: Row 2 is the fold-mirror of Row 1, Row 3 is the centre-reflection of
# Row 2, and Row 4 is the centre-reflection of Row 1. Reflecting a row across the
# centre maps ty -> H - ty and flips sy. All four rows are emitted as their own
# animatable groups (no passive <use>), so every letter animates independently —
# the JS mutates one letter at a time across all sixteen, with no coupling.
ROW1 = {"ty": C, "sy": -1}                # upright,  occupies [0, C]
ROW2 = {"ty": C - BAR, "sy": 1}           # flipped,  occupies [C-BAR, 2C-BAR]
ROW3 = {"ty": 3 * C - 2 * BAR, "sy": -1}  # reflection of Row 2 across the centre
ROW4 = {"ty": 3 * C - 3 * BAR, "sy": 1}   # reflection of Row 1 across the centre


def row(rid, cls, ty, sy):
    parts = [f'    <g id="{rid}" class="{cls}">']
    for i, g in enumerate(L):
        parts.append(
            f'      <g class="mk-letter" data-i="{i}" transform="translate({xs[i]},{ty}) scale(1,{sy})">'
            f'<g class="mk-glyph"><path d="{g["path"]}"/></g></g>'
        )
    parts.append("    </g>")
    return "\n".join(parts)


svg = f'''{{{{- /* GENERATED by scripts/generate-mark.py from Nasalization — do not edit by hand.
       Regenerate with `make mark`. The SARC four-row mark; see CLAUDE.md
       "Live landing mark". All four rows are emitted as their own animatable
       groups so every letter animates independently (one letter mutates at a
       time across all sixteen). Rows are reflected across the figure's centre
       in pairs (Row 2 of Row 1, Row 3 of Row 2, Row 4 of Row 1). Adjacent rows
       overlap by exactly one horizontal-bar height. */ -}}}}
<div class="mark" data-mark>
  <svg class="mark-svg" viewBox="0 0 {W} {H}" role="img"
       aria-label="SARC — Studio for Advanced Research in Cybernetics"
       preserveAspectRatio="xMidYMid meet">
    <title>SARC</title>
    <desc>The letters s a r c, reflected across a central axis.</desc>
{row("mk-row1", "mark-row", ROW1["ty"], ROW1["sy"])}
{row("mk-row2", "mark-row", ROW2["ty"], ROW2["sy"])}
{row("mk-row3", "mark-row", ROW3["ty"], ROW3["sy"])}
{row("mk-row4", "mark-row", ROW4["ty"], ROW4["sy"])}
  </svg>
</div>
'''

with open(OUT, "w") as f:
    f.write(svg)

print(f"✓ mark: wrote {os.path.relpath(OUT, ROOT)}  (viewBox {W}×{H}, bar {BAR}, axis {H/2:g})")


# --- Wordmark ---------------------------------------------------------------
# The header/footer "SARC" logotype, baked from the same font to outline paths.
# The free Typodermic licence permits creating a logo but NOT embedding the font
# in a web page, so — like the mark — we ship outlines, never the font file.
U = [glyph(c) for c in "SARC"]
uy0 = min(g["bounds"][1] for g in U)          # baseline / descent
uy1 = max(g["bounds"][3] for g in U)          # cap top
wx, ux = [], 0
for g in U:
    wx.append(ux)
    ux += g["adv"] + WTRACK
xmin = min(wx[i] + U[i]["bounds"][0] for i in range(len(U)))   # tight left crop
xmax = max(wx[i] + U[i]["bounds"][2] for i in range(len(U)))   # tight right crop
VBW = xmax - xmin
WH = uy1 - uy0

wglyphs = "".join(
    f'<g transform="translate({wx[i]},0)"><path d="{U[i]["path"]}"/></g>'
    for i in range(len(U))
)
word = f'''{{{{- /* GENERATED by scripts/generate-mark.py from Nasalization — do not edit by hand.
       Regenerate with `make mark`. The "SARC" wordmark used in the header and
       footer, baked to outline paths (fill: currentColor). The font is used
       only at build time to produce this logo; it is never embedded or shipped
       (the free Typodermic licence forbids web-page font embedding). */ -}}}}
<svg class="wordmark-svg" viewBox="{xmin} 0 {VBW} {WH}" aria-hidden="true" focusable="false" preserveAspectRatio="xMinYMid meet"><g transform="matrix(1,0,0,-1,0,{uy1})">{wglyphs}</g></svg>
'''

with open(WORD_OUT, "w") as f:
    f.write(word)

print(f"✓ wordmark: wrote {os.path.relpath(WORD_OUT, ROOT)}  (viewBox {VBW}×{WH})")
